export const FETCH_FILMS_START = 'FETCH_FILMS_START';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_ERROR = 'FETCH_FILMS_ERROR';


export const FILM_SELECTED_START = 'FILM_SELECTED_START';
export const FILM_SELECTED_SUCCESS = 'FILM_SELECTED_SUCCESS';
export const FILM_SELECTED_ERROR = 'FILM_SELECTED_ERROR';

export const OPEN_MODAL = 'OPEN_MODAL';